name = "template"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "d1-demo"
database_id = "3a814d86-5af9-49bc-9615-f68fc64b4b70"