name = "template"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "template-demo"
database_id = "7dbecfea-29e2-43a2-a8a9-7af3f63b3818"